### ISSUE TITLE
`cargo build --release` fails

### ISSUE THREAD

**Issue by ZanSara** [toshokan/spookylock#2]
After a fresh clone of the project, executing `cargo build --release` results in the following:

```
error[E0432]: unresolved import `syn::export`
  --> /home/sara/.cargo/registry/src/github.com-1ecc6299db9ec823/enumset_derive-0.4.4/src/lib.rs:10:10
   |
10 | use syn::export::Span;
   |          ^^^^^^ could not find `export` in `syn`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `enumset_derive` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed
```

I'm no Rust expert, so please advise me on how to proceed. I'll notify if I find a bugfix.

cargo version: 1.55.0 (32da73ab1 2021-08-23)
OS: Ubuntu 21.04

**Comment by toshokan** [comment]
Thank you for reporting this. 
Sorry for the long delay, this was due to Lymia/enumset#17

Should be fixed in 51fd250
